### ISSUE TITLE
Include this to "Reformat Code"

### ISSUE THREAD

**Issue by mriehema** [anton-rudeshko/CSSReorder#10]
It would be nice, if CSSComb is called automatically during the "Reformat Code" Action and doesn't be called separately.

**Comment by anton-rudeshko** [comment]
Yeah, i'm agree with you, that would be very nice. 
But right now i have no idea how to implement it. 
There is no comprehensive docs nor sources for CSS support in IntelliJ IDEA platform AFAIK =(

**Comment by axelcostaspena** [comment]
I tried it. In the reformat options dialog, if I select the radio button "Current file", the "rearrange checkbox" enabled. But if I select "Selected text" or "All files in current directory", the checkbox is disabled.

**Comment by anton-rudeshko** [comment]
Yeah, that's sad. But i'm not in control of this dialog. We should request such feature.

**Comment by anton-rudeshko** [comment]
See http://youtrack.jetbrains.com/issue/IDEA-109966

**Comment by axelcostaspena** [comment]
Great @anton-rudeshko!
