### ISSUE TITLE
Can't assign a shortcut to "Rearrange code"

### ISSUE THREAD

**Issue by axelcostaspena** [anton-rudeshko/CSSReorder#14]
After https://github.com/anton-rudeshko/CSSReorder/issues/7, whenever I try to assign a keymap to the "Rearrange code" action, it asks me to restart the IDE to make plugins accept changes, but after restarting keymap is lost.

**Comment by axelcostaspena** [comment]
Surprisingly, if I postpone restarting, keymap is correctly assigned. And if later I close and reopen IDE, voilá! Keymap is kept. So the only action that breaks the keymap is the restart ;)

**Comment by anton-rudeshko** [comment]
Hmm, i don't think that it's related to plug-in.
IDEA should not ask for restart after keymap change. Contact JetBrains support.
