### ISSUE TITLE
Not working in Webstorm 7 

### ISSUE THREAD

**Issue by cubeweb** [anton-rudeshko/CSSReorder#16]
First of all great plugin.

Maybe is too early, but it doesn't seem to work on Webstorm 7 EAP. I get that error 'NoClassDefFoundError: com/intellij/psi/codeStyle/arrangement/settings/ArrangementStandardSettingsAware'.

It works fine in Phpstorm 6.

Thanks

**Comment by anton-rudeshko** [comment]
Thanks for report. Will check for solutions

**Comment by thasmo** [comment]
Also doesn't work on PHPStorm 7 EAP.

```
NoClassDefFoundError: com/intellij/psi/codeStyle/arrangement/settings/ArrangementStandardSettingsAware: com/intellij/psi/codeStyle/arrangement/settings/ArrangementStandardSettingsAware
```

**Comment by danny-englander** [comment]
I'm not seeing an error message with PHPStorm 7 EAP, but `Code > Rearrange Code` is simply greyed out from the code menu even though all my CSS is selected in my file, not sure if this is a related issue or if I should file a new one.

**Comment by axelcostaspena** [comment]
Yeah, for me, since the first versions of PHPStorm 7 EAP, I saw the checkbox disabled and the error arises.

**Comment by hugosaner** [comment]
I'm crossing my fingers that Anton can work his magic, I use this plugin so much to keep my stylesheets organized.

**Comment by anton-rudeshko** [comment]
Thank you guys for your patience!
 I'll fix this for WS7 and PS7 ASAP!

**Comment by anton-rudeshko** [comment]
I've just committed fix for this issue and will release new version, stay tuned for update. 
Keep in touch! Thanks

**Comment by axelcostaspena** [comment]
Great news! Thank you anton!

**Comment by anton-rudeshko** [comment]
Please tell me that it works fine for you guys =)

**Comment by cubeweb** [comment]
Test it in both Phpstorm and Webstorm 7 and it works fine.
Thanks Anton

**Comment by cyberchimps** [comment]
Anton, you star!!!! works a treat and now not only are my stylesheets more organised but I feel more organised.

Thank you so much for fixing it so quickly :)

**Comment by hugosaner** [comment]
Works perfectly thank you Anton!!!

**Comment by anton-rudeshko** [comment]
Thanks you so much for your positive feedback!
