### ISSUE TITLE
Update with new csscomb version

### ISSUE THREAD

**Issue by johannesjo** [anton-rudeshko/CSSReorder#19]
Would be very nice for better sass and less support.

**Comment by anton-rudeshko** [comment]
@johannesjo unfortunately CSSReorder have no shared codebase with CSScomb, so I can't just "update it", I need to implement it from scratch. For now it's pretty hard for me, sorry.

What exactly do you mean by "better support"? I'll try to do my best.

**Comment by johannesjo** [comment]
@anton-rudeshko thank you for your reply. Unfortunately I can't test it right now, as the plugin doesn't seem to work with IntelliJ 13.4 at all, but as I remember it really messed up indentation.

**Comment by anton-rudeshko** [comment]
Hmm, that's strange, could you please tell me how can I reproduce that? Or it doesn't work at all even with just css? 
I'll have a look at it tomorrow.
**upd** Seems to work fine with IDEA 135.1230, tested several simple cases with css, less and sass.

**Comment by johannesjo** [comment]
Reinstalling the plugin somehow did the trick for me. It even works with the sass syntax. Thank you very much for this useful plugin.

**Comment by anton-rudeshko** [comment]
Heh, maybe you have accidentally disabled auto update?
Thanks for your kind words and your feedback, have a nice day!
I'm closing this issue for now, keep in touch
