### ISSUE TITLE
Work with ".scss" SASS files

### ISSUE THREAD

**Issue by christianmagill** [anton-rudeshko/CSSReorder#5]
CSS Comb Supports SASS. Can you update the extension to work with .scss files.

Thanks

**Comment by christianmagill** [comment]
+1

**Comment by anton-rudeshko** [comment]
I've implemented correct way of detecting a file type (at b702a433154f291bfa9bbc14f63e692187ac6cf8) and plugin _may_ now _basically_ work with scss. But right scss is not targeted.
Feel free to check it out (in future minor version) and report.

**Comment by anton-rudeshko** [comment]
More solid support in 0.4.0
