### ISSUE TITLE
why is "!important" removed?

### ISSUE THREAD

**Issue by ghost** [anton-rudeshko/CSSReorder#6]
hello,

"Apply CssComb" removes my !important code.
can i configure it, not to do that?

**Comment by isprogfun** [comment]
I have a same problem. Is where an options for this plugin?

**Comment by miripiruni** [comment]
Oh, my... :( 

+1

**Comment by anton-rudeshko** [comment]
Hi guys!
Options page is in progress, right now plugin is in very early dev stage.
Thank you for using it, testing and reporting! 
Will fix it asap!

**Comment by miripiruni** [comment]
"asap" means about 2 weeks. Anton on vacation without laptop :)

**Comment by anton-rudeshko** [comment]
I'll deploy this change later on and please feel free to check it out.
Thanks
