### ISSUE TITLE
Critical

### ISSUE THREAD

**Issue by miripiruni** [anton-rudeshko/CSSReorder#8]
Антон, привет!
Сейчас этот плагин не работает. Ты собираешься его дописывать?
Если не уверен, то давай удалим его из списка плагинов JetBrains? Там люди его ставят, а он не работает :(

**Comment by anton-rudeshko** [comment]
Хм, а я что-то и не в курсе? Мне никто не жаловался. У кого не работает?
У меня на 12-й идее всё работает
Допиливать собираюсь, но пока не могу выделить ресурсы.

**Comment by miripiruni** [comment]
Молчат.

Смотри https://github.com/anton-rudeshko/CSSComb/issues/11 например

**Comment by miripiruni** [comment]
Привет, еще раз.

Хотел узнать какие у тебя планы на этот плагин. Сейчас все репозитории имеющие отношение к расческе переехали в организацию https://github.com/csscomb там живет и ядро и обертки для плагинов. Я предлагаю перенести этот репозиторий тоже. Но при условии, что ты готов им заниматься.

**Comment by anton-rudeshko** [comment]
Привет, планы радужные, со слониками. Но сроков нет.

Переезжать не готов, потому что:
- плагин — не обёртка, а standalone;
- опять же, заниматься готов (не забрасывать), но пока совсем не выходит и не хочется давать невыполнимых обещаний.

**Comment by miripiruni** [comment]
Ок.

Тогда давай ты переименуешь это дело в репозитории плагинов JetBrains из CSScomb во что-то другое на время, пока это начнет работать как CSScomb? Я очень переживаю, что народ ищет по имени CSScomb, скачивает, пробует, а там не совсем оно :'(

**Comment by miripiruni** [comment]
Я даже сам поменял имя, если ты не против. Закрываю.

**Comment by anton-rudeshko** [comment]
Да, хорошо, хотел это сам предложить. Спасибо

**Comment by miripiruni** [comment]
Если созреешь переезжать в организацию — пиши обязательно.

**Comment by anton-rudeshko** [comment]
Конечно, сорри если запятнал оригинальный плагин. В ближайшее время переименуюсь глубже.
