### ISSUE TITLE
Add default Shortcut

### ISSUE THREAD

**Issue by mriehema** [anton-rudeshko/CSSReorder#9]
Please add a default Shortcut (Keymapping) for this Plugin.

**Comment by miripiruni** [comment]
In other plugins I use `Shift + Ctrl + C`. It would be OK?

@anton-rudeshko can you add shortcut?

**Comment by anton-rudeshko** [comment]
@miripiruni, unfortunately `Shift + Ctrl + C` is already taken in default keymap.
@mriehema, which do you propose? Maybe `Alt + C`?
